### ISSUE TITLE
Remote I/O

### ISSUE THREAD

**Issue by jmFschneider** [adafruit/Adafruit_CircuitPython_VEML6075#11]
Hello,

I have a PI running from 5 days without any issue regulating a temperature in a small garden room (hotroom ?).

This night I have the following error : 

 

> Traceback (most recent call last):
>   File "/home/pi/Documents/Python/Temperature/RegulHumidLumino.py", line 81, in <module>
>     temp = str(temperature) + '\t' + str(temperature2) + '\t' + str(temperature3) + '\t' + str(EtatChauffage) + '\t' + str(Lux.value) + '\t' + str(Hum.value)
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_ads1x15/analog_in.py", line 74, in value
>     is_differential=self.is_differential) << (16 - self._ads.bits)
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_ads1x15/ads1x15.py", line 137, in read
>     return self._read(pin)
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_ads1x15/ads1x15.py", line 166, in _read
>     while not self._conversion_complete():
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_ads1x15/ads1x15.py", line 176, in _conversion_complete
>     return self._read_register(_ADS1X15_POINTER_CONFIG) & 0x8000
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_ads1x15/ads1x15.py", line 202, in _read_register
>     i2c.write_then_readinto(bytearray([reg]), self.buf, in_end=2)
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 141, in write_then_readinto
>     in_start=in_start, in_end=in_end)
>   File "/usr/local/lib/python3.5/dist-packages/busio.py", line 92, in writeto_then_readfrom
>     in_start=in_start, in_end=in_end, stop=stop)
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 61, in writeto_then_readfrom
>     readin = self._i2c_bus.read_i2c_block_data(address, buffer_out[out_start:out_end], in_end-in_start)
>   File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO/smbus.py", line 227, in read_i2c_block_data
>     ioctl(self._device.fileno(), I2C_RDWR, request)
> OSError: [Errno 121] Remote I/O error

If I understand well the I2C slave was not seen, but, I run again this morning this application without issue.
So I am confuse of what is appnening !

Can you help me on this subject ? How can I have more precise idea of what was appining this night ?

Thanks you,
Jean-Marie

**Comment by jmFschneider** [comment]
I write this message not a the good level, but not such where to place it ... and I don't see the possibility to move it. 

Can an administrator move this message to a better place if needed ?

Sorry for the unconvenience !
And thanks you for your help
Jean-Marie
